services:

  postgres-service:
    image: postgres:17
    container_name: postgresql-hotel-service-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  hotel-service:
    build: .
    image: docker-hotel-service:4.0
    ports:
      - "6063:6062"
    environment:
      SERVER_PORT: 6062
      DB_HOST: postgres-service
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: root
      DB_NAME: postgres
      DB_SCHEMA_NAME: hm-hotel-service

volumes:
  postgres-data: